[workspace]
resolver = "2"
members = [
    "crates/proto",
    "crates/resolver",
    "crates/recursor",
    "crates/client",
    "crates/server",
    "crates/async-std-resolver",
    "bin",
    "util",
    "tests/compatibility-tests",
    "tests/integration-tests",
    "tests/test-support",
]
exclude = ["fuzz"]

[workspace.package]
version = "0.25.0-alpha.2"
authors = ["The contributors to Hickory DNS"]
edition = "2021"
rust-version = "1.70"
homepage = "https://hickory-dns.org/"
repository = "https://github.com/hickory-dns/hickory-dns"
keywords = ["DNS", "BIND", "dig", "named", "dnssec"]
categories = ["network-programming"]
license = "MIT OR Apache-2.0"


[workspace.dependencies]
# hickory
hickory-client = { version = "0.25.0-alpha.2", path = "crates/client", default-features = false }
hickory-recursor = { version = "0.25.0-alpha.2", path = "crates/recursor", default-features = false }
hickory-resolver = { version = "0.25.0-alpha.2", path = "crates/resolver", default-features = false }
hickory-server = { version = "0.25.0-alpha.2", path = "crates/server", default-features = false }
hickory-proto = { version = "0.25.0-alpha.2", path = "crates/proto", default-features = false }
test-support.path = "tests/test-support"


# logging
tracing = { version = "0.1.37", default-features = false }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
thiserror = { version = "1.0.63", default-features = false, git = "https://github.com/quartiq/thiserror.git", rev = "44737a516b7fd0cc9dabcab07e7b1f927f8f5636" }

# async/await
async-recursion = "1.0.0"
async-trait = "0.1.43"
futures = { version = "0.3.5", default-features = false }
futures-channel = { version = "0.3.5", default-features = false }
futures-executor = { version = "0.3.5", default-features = false }
futures-io = { version = "0.3.5", default-features = false }
futures-util = { version = "0.3.5", default-features = false }
async-std = "1.6"
tokio = "1.21"
tokio-native-tls = "0.3.0"
tokio-openssl = "0.6.0"
tokio-rustls = { version = "0.26", default-features = false }
tokio-util = "0.7.9"
parking_lot = "0.12"
pin-project-lite = "0.2"


# ssl
native-tls = "0.2"
openssl = "0.10.55"
rustls = { version = "0.23", default-features = false, features = [
    "logging",
    "std",
    "tls12",
] }
rustls-native-certs = "0.7"
rustls-pemfile = "2"
webpki-roots = "0.26"
ring = "0.17"


# net proto
quinn = { version = "0.11.2", default-features = false }
h2 = "0.4.0"
h3 = "0.0.6"
h3-quinn = "0.0.7"
http = "1.1"


# others
backtrace = "0.3.50"
bitflags = "2.4.1"
bytes = "1"
cfg-if = "1"
clap = { version = "4.0", default-features = false }
console = "0.15.0"
data-encoding = { version = "2.2.0", default-features = false }
enum-as-inner = "0.6"
idna = { version = "1.0.2", default-features = false, features = ["alloc", "compiled_data"] }
ipconfig = "0.3.0"
ipnet = { version = "2.3.0", default-features = false }
js-sys = "0.3.44"
once_cell = { version = "1.18.0", default-features = false }
lru-cache = "0.1.2"
pin-utils = "0.1.0"
prefix-trie = "0.4"
radix_trie = "0.2.0"
rand = { version = "0.8", default-features = false, features = ["std_rng", "alloc"] }
regex = { version = "1.3.4", default-features = false }
resolv-conf = "0.7.0"
rusqlite = "0.32"
serde = "1.0"
smallvec = "1.6"
socket2 = "0.5"
time = "0.3"
tinyvec = "1.1.1"
toml = "0.8.14"
url = { git = "https://github.com/domenukk/rust-url.git", default-features = false, rev = "c79a0d63caf9bc10f39dec524e3336465238b62c" }
wasm-bindgen-crate = { version = "0.2.58", package = "wasm-bindgen" }

[patch.crates-io]
# tokio = { path = "../tokio/tokio" }
# mio = { git = "https://github.com/tokio-rs/mio.git" }
# h2 = { git = "https://github.com/hyperium/h2.git" }

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
strip = "symbols"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(nightly)'] }
